export const NEW_FILE_UPLOAD_START = 'NEW_FILE_UPLOAD_START';
export const NEW_FILE_UPLOAD_SUCCESS = 'NEW_FILE_UPLOAD_SUCCESS';
export const NEW_FILE_UPLOAD_FAIL = 'NEW_FILE_UPLOAD_FAIL';
export const SPLIT_PARSED_DATA = 'SPLIT_PARSED_DATA';
