export const NEW_FILE_UPLOAD_START = 'NEW_FILE_UPLOAD_START';
export const NEW_FILE_UPLOAD_SUCCESS = 'NEW_FILE_UPLOAD_SUCCESS';
export const NEW_FILE_UPLOAD_FAIL = 'NEW_FILE_UPLOAD_FAIL';
export const ADD_NEW_FILE_NAME = 'ADD_NEW_FILE_NAME';
export const SPLIT_PARSED_DATA = 'SPLIT_PARSED_DATA';
export const SET_FIELD_TYPES = 'SET_FIELD_TYPES';
export const UPDATE_USER_DEF_FIELD_TYPES = 'UPDATE_USER_DEF_FIELD_TYPES';

export const FILES_READY_TO_UPLOAD = 'FILES_READY_TO_UPLOAD';
export const FILES_NOT_READY_TO_UPLOAD = 'FILES_NOT_READY_TO_UPLOAD';
