export const SET_USER_TABLES_DATA = 'SET_USER_TABLES_DATA';

export const SET_COLUMN_AS_X_AXIS = 'SET_COLUMN_AS_X_AXIS';
export const MOVE_COLUMN_TO_LEGENDS = 'MOVE_COLUMN_TO_LEGENDS';
export const MOVE_COLUMN_TO_TABLES = 'MOVE_COLUMN_TO_TABLES';
