export const SET_USER_TABLES_DATA = 'SET_USER_TABLES_DATA';

export const SET_COLUMN_AS_X_AXIS = 'SET_COLUMN_AS_X_AXIS';
export const MOVE_COLUMN_TO_LEGENDS = 'MOVE_COLUMN_TO_LEGENDS';
export const MOVE_COLUMN_TO_TABLES = 'MOVE_COLUMN_TO_TABLES';

export const SET_COLUMN_DATA = 'SET_COLUMN_DATA';

export const ADD_DATA_SET = 'ADD_DATA_SET';
export const REMOVE_DATA_SET = 'REMOVE_DATA_SET';

export const UPDATE_GRAPH_TYPE = 'UPDATE_GRAPH_TYPE';

export const UPDATE_Y_AXIS_STACK_OPT = 'UPDATE_Y_AXIS_STACK_OPT';

export const TOGGLE_TITLE_DISPLAY = 'TOGGLE_TITLE_DISPLAY';
export const UPDATE_DISPLAY_TEXT = 'UPDATE_DISPLAY_TEXT';
export const UPDATE_DISPLAY_POSITION = 'UPDATE_DISPLAY_POSITION';
export const UPDATE_DISPLAY_FONT_SIZE = 'UPDATE_DISPLAY_FONT_SIZE';
export const UPDATE_DISPLAY_FONT_COLOUR = 'UPDATE_DISPLAY_FONT_COLOUR';
