/**Exports all actions for convenience. */
export {
  setUserTablesData,
  setColumnAsXAxis,
  moveColumnToLegends,
  moveColumnToTables,
  setColumnData,
  addDataSet,
  reAggregate,
  unAggregate,
  updateDataSetColour,
} from './graphData';

export {
  updateGraphType,
  updateYAxisStackOpt,
  toggleTitleDisplay,
  updateDisplayText,
  updateDisplayPosition,
  updateDisplayFontSize,
  updateDisplayFontColour,
  toggleLegendDisplay,
  updateLegendPosition,
  updateLegendAlignment,
  toggleAxisLabelDisplay,
  updateAxisLabel,
  updateAxisFontColour,
  updateAxisFontSize,
  toggleAxisGridDisplay,
  updateAxisGridLineWidth,
  updateAxisGridLineColour,
  updateAxisGrid0LineWidth,
  updateAxisGrid0LineColour,
  updateAggregationMethod,
} from './graphOptions';
